[package]
name = "compose"
version = "0.1.0"
authors = ["AndrewRademacher <andrewrademacher@icloud.com>"]
edition = "2018"

[dependencies]
rodio = "^0.13"
ndarray = { version = "^0.14", features = ["rayon"] }
rayon = "^1.5"
hound = "^3.4"
nom = "^6.0"
